### ISSUE TITLE
unimrcp with plugin xfyun has problems

### ISSUE THREAD

**Issue by shanghai-Jerry** [wangkaisine/mrcp-plugin-with-freeswitch#6]
` Load Plugin [xfyunsynth-1] [/usr/local/unimrcp/plugin/xfyunsynth.so]
Failed to Load DSO: /usr/local/unimrcp/lib/libmsc.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE 
Load Plugin [xfyunrecog-1] [/usr/local/unimrcp/plugin/xfyunrecog.so]
Failed to Load DSO: /usr/local/unimrcp/lib/libmsc.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE`

**Comment by kvi111** [comment]
我也碰到这个问题了，怎么解决？

**Comment by kvi111** [comment]
应该是编译的是有问题

**Comment by kvi111** [comment]
xfyun_synth_engine.c 
311行，第二个参数增加强制转换(void*) 
mpf_buffer_audio_write(buffer,(void*)data, audio_len);

xfyun_recog_engine.c
将488行开始的函数 xfyun_recog_end_session 整块移到 366行 xfyun_recog_channel_stop 这个函数前面

**Comment by shanghai-Jerry** [comment]
据说是现在讯飞不支持unimrcp的协议

**Comment by kvi111** [comment]
查看讯飞demo编译选项，比参考中多了一个：-lmsc -ldl -lpthread -lrt -lstdc++ ，就是最后那个stdc++，加上之后，OK。

**Comment by shanghai-Jerry** [comment]
> 查看讯飞demo编译选项，比参考中多了一个：-lmsc -ldl -lpthread -lrt -lstdc++ ，就是最后那个stdc++，加上之后，OK。

yes,  wonderful work
